config/routes.rb
Rails.application.routes.draw do

  root "home#index"  

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "about", to: "home#about"
  get "contact", to: "home#contact"
  
  get "signup", to: "users#new"
  post "signup", to: "users#create" 

  resources :users, except: [:index, :new, :create, :destroy]
  resources :posts, except: [:edit, :update] do
    resources :comments, shallow: true, only: [:create, :destroy]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  attr_accessor :user_image_cache
  before_save { self.email = email.downcase }
  has_secure_password

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  mount_uploader :user_image, UserimageUploader
  
  validates :name,
    presence: { message: "Please fill out." },
    uniqueness: { message: "Someone has already used." },
    length: { maximum: 25 },
    on: :create

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, 
    presence: { message: "Please fill in your email" },
    uniqueness: { 
      case_sensitive: false,
      message: "Someone has already used."},
    confirmation: true,
    format: { with: VALID_EMAIL_REGEX, message: " is invalid." },
    length: { maximum: 255 },
    on: :create

  validates :password,
    presence: { message: "Please fill out." },
    length: { minimum: 6 },
    on: :create

  validates :email_confirmation, :password_confirmation,
    presence: true,
    on: :create
    
  validates :user_image, {
    file_size: {
      less_than_or_equal_to: 1.megabyte,
      message: 'image should be less than %{count}'},
    file_content_type: { 
      allow: ["image/jpeg", "image/jpg", "image/png", "image/gif"],
      # mode: :strict,
      message: 'only %{types} are allowed'},
  }

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def self.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :confirm_login, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]
  before_action :confirm_logout, only: [:new, :create]
  # before_action :method_out_of_service, only: [:update] 

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      reset_session
      log_in(@user)
      redirect_to("/posts")
      flash[:notice] = "Welcome, #{current_user.name}!"
    else
      flash.now[:notice] = "I'm sorry there seems to be something wrong"
      render("/users/new")
    end
  end
  
  def show
    @user = User.find_by(id: params[:id])
    @user_posts = @user.posts.order(created_at: :desc)
  end

  
  def edit
    @user = current_user
  end
  
  def update
    @user = User.find_by(id: params[:id])
    User.transaction do
      @user.remove_user_image
      @user.update_attributes!(user_params)
    end
    redirect_to user_path(@user)
    flash[:notice] = "Change your image!"
    rescue ActiveRecord::RecordInvalid => e
      flash.now[:notice] = "Failed"
      render("/users/edit")
      puts "#{e.class}: #{e.message}"
      puts e.backtrace
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :email_confirmation, :password, :password_confirmation, :user_image)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper

  # def forbid_access_user
  #   if current_user.id != params[:id].to_i
  #     flash[:notice] = "I'm sorry you're not allowed this"
  #     redirect_to("/posts/index")
  #   end
  # end

end

app/views/users/edit.html.erb
<div class="main posts-index">
  <div class="container">
    <div class="user-info">
      <% if !@user.user_image.blank? %>
        <%= image_tag(@user.user_image_url.to_s, class: "posts-each-user-image", style:"width=10vw;") %>
      <% else %>
        <p style="font-size: 50px"><i class="fas fa-user" ></i></p>
      <% end %>
      <P style="font-size: 50px"> <%= @user.name %> </P>

      <%= form_for @user, url: user_path(@user), html: { multipart: true, method: "patch" } do |f| %>
        <%= f.file_field :user_image %>
        <%= f.hidden_field :user_image_cache %>
        <%= f.submit "Change your image" %>
      <% end %>
      
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="main signup">
  <div class="container">
    <div class="signup-box">
      <div class="signup-box-header">
        Sign up
      </div>
      <%= form_for(@user, url: signup_path) do |f| %>
      <div class="signup-box-contents">
        <div class="signup-box-contents-left">
          <div class="signup-box-contents-content">
            <%= f.label :name %>
            <%= f.text_field :name, value: @user.name, autocomplete: :off %>
          </div>
          <div class="signup-box-contents-content">
            <%= f.label :email %>
            <%= f.email_field :email, value: @user.email, autocomplete: :off %>
          </div>
          <div class="signup-box-contents-content"> 
            <%= f.label :email_confirmation %>
            <%= f.email_field :email_confirmation, value: @user.email_confirmation, autocomplete: :off %>
          </div>
          <div class="signup-box-contents-content">
            <%= f.label :password %>
            <%= f.password_field :password, value: @user.password %>
          </div>
          <div class="signup-box-contents-content">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, value: @user.password_confirmation %>
          </div>
        </div><!--  
      --><div class="signup-box-contents-right">
          <%= f.submit "Signup", class:"btn submit-login" %>
          <ul>
          <% @user.errors.full_messages.each do |error| %>
            <li style="color: red; font-size: 14px;"><%= error %></li>
          <% end %>
          </ul>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main posts-index">
  <div class="container">
    <div class="user-info">
      <% if !@user.user_image.blank? %>
        <%= image_tag(@user.user_image_url.to_s, class: "posts-each-user-image") %>
      <% else %>
        <p style="font-size: 50px"><i class="fas fa-user" ></i></p>
      <% end %>
      <P style="font-size: 50px"> <%= @user.name %> </P>
      <% if current_user %>
        <% if @user.id === current_user.id %>
          <%= link_to "Edit your image", "/users/#{@user.id}/edit", style:"font-size: 15px; color: rgba(0,0,0,0.6)" %>
        <% end %>
      <% end %>
    </div>
    <% @user_posts.each do |user_post| %>
      <div class="posts-each">
        <%= render "shared/post", post: user_post %>
        <% if current_user?(@user) %>
          <div class="posts-each-edit">
            <%= link_to "Delete", post_path(user_post), method: :delete, data: {confirm: "Are you sure?"}, style: "font-size: 15px; color: rgba(0,0,0,0.6);" %> 
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>