config/routes.rb
Rails.application.routes.draw do

  root "home#index"  

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "about", to: "home#about"
  get "contact", to: "home#contact"
  
  get "signup", to: "users#new"
  post "signup", to: "users#create" 

  resources :users, except: [:index, :new, :create, :destroy]
  resources :posts, except: [:edit, :update] do
    resources :comments, shallow: true, only: [:create, :destroy]
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessor :post_image_cache
  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :post_image, PostimageUploader
  
  validates :user_id, :content, presence: true
  validates :post_image, {
    file_size: {
      less_than_or_equal_to: 1.megabyte,
      message: 'should be less than %{count}'},
    file_content_type: { 
      allow: ["image/jpeg", "image/jpg", "image/png", "image/gif"],
      # mode: :strict,
      message: 'only %{types} are allowed'},
  }

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :confirm_login, { only: [:new, :create] }
  before_action :forbid_access_posts, { only: [:destroy] }
  # before_action :method_out_of_service, { only: [:create] }

  def index
    @posts = Post.all.order(created_at: :desc)
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    
    if @post.save
      redirect_to posts_path
      flash[:notice] = "just posted!"
    else
      flash.now[:notice] = "Failed..."
      render("/posts/new")
    end
  end
  
  def show
    @post = Post.find_by(id: params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end
  
  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to posts_path
  end
  
  private
    def post_params
      params.require(:post).permit(:content, :post_image).merge(user_id: session[:user_id])
    end

    def forbid_access_posts
      @post = Post.find_by(id: params[:id])
      unless current_user?(@post.user)
        redirect_to posts_path
        flash[:notice] = "I'm sorry you're not allowed this"
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  
end

app/views/posts/index.html.erb
<div class="main posts-index">
  <div class="container">
  <% if @posts %>
    <% @posts.each do |post| %>
      <div class="posts-each">
        <%= link_to post_path(post), { class: "btn post-detail-link" } do %>
          <%= render "shared/post", post: post %> 
        <% end %>
      </div>
    <% end %>
  <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main new-post">
  <div class="container">
    <%= form_for(@post, url: posts_path, multipart: true) do |f| %>
    <div class="new-post-form">
      <div class="new-post-userinfo">
        <img src="">
        <%= session[:user_name] %>
      </div>
      <div class="new-post-text">
        <%= f.label :post_image, "Attached image" %>
        <%= f.file_field :post_image %>
        <%= f.hidden_field :post_image_cache %>
        <!--<input name="post_image" type="file">-->
        <%= f.label :content, "Content" %>
        <%= f.text_area :content %>
        <!--<textarea name="content" type="text"></textarea>-->
      </div>
      <div class="new-post-submit">
        <!--<input type="submit" value="Tweet!">-->
        <%= f.submit "Tweet!" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main posts-index">
  <div class="container">
    <div class="posts-each">
      <%= render "shared/post", post: @post %>
      <% if @comments %>
        <div id="after-commented">
          <%= render "comments/comment" %>
        </div>
      <% end %>
      <%= form_for(@comment, url: post_comments_path(@post), remote: true) do |f| %>
        <div class="posts-each-input-comment">
          <%= f.text_field :comment, id: "text-field-comment", autocomplete: :off %>
          <%= f.submit "Comment!", class: "btn" %>
        </div>
      <% end %>
      <% if current_user?(@post.user) %>
        <div class="posts-each-edit">
          <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, style: "font-size: 15px; color: rgba(0,0,0,0.6);" %> 
        </div>
      <% end %>
    </div>
  </div>
</div>