config/routes.rb
Rails.application.routes.draw do

  root "home#index"  

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "about", to: "home#about"
  get "contact", to: "home#contact"
  
  get "signup", to: "users#new"
  post "signup", to: "users#create" 

  resources :users, except: [:index, :new, :create, :destroy]
  resources :posts, except: [:edit, :update] do
    resources :comments, shallow: true, only: [:create, :destroy]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  after_action :flash_to_headers

  private
    def method_out_of_service
      flash[:notice] = "I'm sorry, this service has been limited now"
      redirect_to("/")
    end
  
    def flash_to_headers
      if request.xhr?
        response.headers["X-Message"] = flash_message
        response.headers["X-Message-Type"] = flash_type.to_s
        flash.discard
      end
    end
    
    def flash_message
      [:error, :warning, :notice].each do |type|
        return flash[type] unless flash[type].blank?
      end
    end
    
    def flash_type
      [:error, :warning, :notice].each do |type|
        return type unless flash[type].blank?
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/application/_flash.html.erb
<% if flash[:notice] %>
  <div id="flash">
    <%= flash[:notice] %>
  </div>
<% end %>

<div id="flash-ajax"></div>

app/views/application/_header_fixed.html.erb
<div class="header-left">
  <%= link_to("MyPhoto", "/", {style: ["font-size: 20px;"]}) %>
</div>
<div class="header-right">
  <span id="menu-bar">
    <i class="fas fa-bars"></i>
  </span>
</div>
<div class="header-fixed-contents">
  <%= render "application/menu_contents" %>
</div>

app/views/application/_header_pc.html.erb
<div class="header-left">
  <%= link_to("MyPhoto", "/", {style: ["font-size: 30px;"]}) %>
</div>
<div class="header-right">
  <%= render "application/menu_contents" %>
</div>

app/views/application/_menu_contents.html.erb
<ul style=" height: 100%;">
  <% if !current_user.nil? %>
    <li><%= link_to("Hello, #{current_user.name}!","/users/#{current_user.id}", class:"btn link") %></li><!--
 --><li><%= link_to("NOW!", "/posts", class:"btn link") %></li><!--
 --><li><%= link_to("Tweet", "/posts/new", class:"btn link") %></li><!--
 --><li><%= link_to("Logout", "/logout", method: :delete, class:"btn link" ) %></li>
  <% else %>
    <li><%= link_to("NOW!", posts_path, class:"btn link") %></li><!--
 --><li><%= link_to("Signup", signup_path, class:"btn link") %></li><!--
 --><li><%= link_to("Login", "/login", class:"btn link") %></li>
  <% end %>
</ul>